<div class="card customized-card">
  <div class="card-header">
    <div class="d-flex justify-content-between align-items-center">
      <h3 class="card-title">Customers</h3>
    </div>
  </div>
  <div class="card-body p-4">
    <div class="col-lg-12">
      <div id="toolbar" class="mb-4 pb-3">
        <a href="#" class="btn btn-primary btn-flat btn-sm create_new me-2"><i class="fa fa-plus-circle me-2"></i>Add</a>
        <a href="#" class="btn btn-outline-success btn-flat btn-sm edit me-2"><i class="fa fa-edit me-2"></i>Edit</a>
        <a href="#" class="btn btn-outline-danger btn-flat btn-sm deletecustomer"><i class="fa fa-trash me-2"></i>Delete Customer</a>
        <a href="#" class="btn btn-dark btn-flat btn-sm depositcustomer"><i class="fa fa-credit-card me-2"></i>Deposit</a>
      </div>
    </div>
    <div class="table-responsive customized-table-container">
      <div id="customertable_wrapper" class="dataTables_wrapper no-footer"><div class="dt-buttons btn-group flex-wrap">          <button class="btn btn-secondary buttons-copy buttons-html5" tabindex="0" aria-controls="customertable" type="button"><span>Copy</span></button> <button class="btn btn-secondary buttons-excel buttons-html5" tabindex="0" aria-controls="customertable" type="button"><span>Excel</span></button> <button class="btn btn-secondary buttons-csv buttons-html5" tabindex="0" aria-controls="customertable" type="button"><span>CSV</span></button> <button class="btn btn-secondary buttons-pdf buttons-html5" tabindex="0" aria-controls="customertable" type="button"><span>PDF</span></button> <button class="btn btn-secondary buttons-print" tabindex="0" aria-controls="customertable" type="button"><span>Print</span></button> </div><div id="customertable_filter" class="dataTables_filter"><label>Search:<input type="search" class="" placeholder="" aria-controls="customertable"></label></div><div id="customertable_processing" class="dataTables_processing" role="status" style="display: none;"><div><div></div><div></div><div></div><div></div></div></div><table id="customertable" class="table display nowrap table-stripped customized-table dataTable no-footer" style="width: 100%;" aria-describedby="customertable_info">
        <thead>
          <tr><th class="sorting sorting_asc" tabindex="0" aria-controls="customertable" rowspan="1" colspan="1" style="width: 189px;" aria-label="Full Name: activate to sort column descending" aria-sort="ascending">Full Name</th><th class="sorting" tabindex="0" aria-controls="customertable" rowspan="1" colspan="1" style="width: 125px;" aria-label="Contact: activate to sort column ascending">Contact</th><th class="sorting" tabindex="0" aria-controls="customertable" rowspan="1" colspan="1" style="width: 231px;" aria-label="Email: activate to sort column ascending">Email</th><th class="sorting" tabindex="0" aria-controls="customertable" rowspan="1" colspan="1" style="width: 184px;" aria-label="Company: activate to sort column ascending">Company</th><th class="sorting" tabindex="0" aria-controls="customertable" rowspan="1" colspan="1" style="width: 146px;" aria-label="Balance (With us): activate to sort column ascending">Balance (With us)</th><th class="sorting" tabindex="0" aria-controls="customertable" rowspan="1" colspan="1" style="width: 109px;" aria-label="Registered By: activate to sort column ascending">Registered By</th><th class="sorting" tabindex="0" aria-controls="customertable" rowspan="1" colspan="1" style="width: 114px;" aria-label="Registered On: activate to sort column ascending">Registered On</th></tr>
        </thead><tbody><tr class="odd"><td class="sorting_1">Mpanga Enatas</td><td>+256 76788867</td><td>dew@gmail.com</td><td>Dew Kicks</td><td>100</td><td>Peter Mukisa</td><td>01 July, 2025</td></tr><tr class="even"><td class="sorting_1">Mulongo Babirye</td><td>+256 767676764</td><td></td><td>DewDreams Bakery</td><td>0</td><td>Peter Mukisa</td><td>01 July, 2025</td></tr><tr class="odd"><td class="sorting_1">Nalweyiso Sandra</td><td>+256764803016</td><td></td><td></td><td>0</td><td>Peter Mukisa</td><td>04 July, 2025</td></tr><tr class="even"><td class="sorting_1">Namutebi Sophia Shantel</td><td>+4567777777</td><td>namutebisophia28@gmail.com</td><td>PEARL TECH SOLUTIONS</td><td>1,500,000</td><td>Peter Mukisa</td><td>28 June, 2025</td></tr></tbody>
      </table><div class="dataTables_info" id="customertable_info" role="status" aria-live="polite">Showing 1 to 4 of 4 entries</div><div class="dataTables_paginate paging_simple_numbers" id="customertable_paginate"><a class="paginate_button previous disabled" aria-controls="customertable" aria-disabled="true" role="link" data-dt-idx="previous" tabindex="-1" id="customertable_previous">Previous</a><span><a class="paginate_button current" aria-controls="customertable" role="link" aria-current="page" data-dt-idx="0" tabindex="0">1</a></span><a class="paginate_button next disabled" aria-controls="customertable" aria-disabled="true" role="link" data-dt-idx="next" tabindex="-1" id="customertable_next">Next</a></div></div>
    </div>
  </div>
</div>